spring.application.name=demo
server.servlet.context-path=/demo/api/

# Database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.database=postgresql
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/daw}
spring.datasource.username=${POSTGRES_USER:daw}
spring.datasource.password=${POSTGRES_PASS:daw}
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always

# Configuacao do Cross Origin Request Site (CORS)
app.cors.allow-credentials=${APP_CORS_ALLOW_CREDENTIALS:false}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:*}
app.cors.allowed-methods=${APP_CORS_ALLOWED_METHODS:*}
app.cors.allowed-headers=${APP_CORS_ALLOWED_HEADERS:*}
